spring.application.name=peluqueriaschedulertest
spring.datasource.url=jdbc:postgresql://localhost:5432/peluqueriaschedulertest
spring.datasource.username=admin
spring.datasource.password=password
spring.flyway.locations=classpath:db/migration/test